[package]
name = "Final_Project_KRB"
version = "0.1.0"
edition = "2024"

[dependencies]
ureq = { version = "2", features = ["json"] }
chrono = { version = "0.4", features = ["clock"] }

[dev-dependencies]
# none